name: Run Python Playwright Project
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Verify installation
        run: |
          python --version
          which xvfb-run
          
      - name: Create .env
        run: |
          cat <<EOF > .env
          LEETCODE_SESSION=${{ secrets.LEETCODE_SESSION }}
          CSRFTOKEN=${{ secrets.CSRFTOKEN }}
          TOKEN_GITHUB=${{ secrets.TOKEN_GITHUB }}
          EOF

      - name: Run main.py
        run: xvfb-run -a python main.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-output
          path: |
            page.html
            page.png
            
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add database/database.db

          git diff --staged --quiet || git commit -m "Update database"

      - name: Push changes
        run: |
          git push origin main
